### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by behnamhsn** [Abbasr7/ngz-shamsi-datepicker#2]
سلام. داداش اول اینکه ممنون بابت شیر کردن پکیجی که توسعه دادی. من دارم ازش استفاده میکنم تو پروژم و یه اروری داره که باعث میشه برنامه من باگی بشه. من کدو بررسی کردم و تصورم اینه توی فایل date-picker.service.ts خط 46 باید باشه مشکل بنظر من. تایپ هایی که دادی با هم نمیخونه. اروری هم که دریافت میکنم اینه : 
value.map is not a function
    at _DatePickerService.makeValue (ngz-shamsi-datepicker.mjs:16793:28)
    at _NzDatePickerComponent.setValue (ngz-shamsi-datepicker.mjs:19991:45)
    at _NzDatePickerComponent.writeValue (ngz-shamsi-datepicker.mjs:19937:10)
    at onChange (forms.mjs:3329:23)
    at forms.mjs:3822:42
    at Array.forEach (<anonymous>)
    at FormControl2.setValue (forms.mjs:3822:22)
    at forms.mjs:4347:20
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:15659:25)

**Comment by Abbasr7** [comment]
باسلام و وقت بخیر
ممکنه سناریویی رو که توش با این باگ مواجه شدید توضیح بدید همچنین رفتار پلیج تو سناریو

**Comment by thealirexa** [comment]
سلام وقتت بخیر @Abbasr7 
ببین این یه مشکل تو سورس پروژه ت هستش. همونطور که بهنام اشاره کرد ظاهرا تو  فایل date-picker.service.ts خط 46 این خطا به وجود میاد. و وقتی که این خطا به وجود میاد به شکل عجیبی مومنت تو کل پروژه خراب میشه و دیگه درست کار نمیکنه !
این خطا توی کنسول چاپ میشه
`value.map is not a function
at _DatePickerService.makeValue (ngz-shamsi-datepicker.mjs:16793:28)
at _NzDatePickerComponent.setValue (ngz-shamsi-datepicker.mjs:19991:45)
at _NzDatePickerComponent.writeValue (ngz-shamsi-datepicker.mjs:19937:10)
at onChange (forms.mjs:3329:23)
at forms.mjs:3822:42
at Array.forEach ()
at FormControl2.setValue (forms.mjs:3822:22)
at forms.mjs:4347:20
at _ZoneDelegate.invoke (zone.js:369:28)
at Object.onInvoke (core.mjs:15659:25)`
ممنونم از پیگیریت عباس جان

**Comment by Abbasr7** [comment]
سلام دوستان خودم یه پکیج Datepicker برای انگولار نوشتم و نسخه جدیدشو منتشر کردم، میتونید از اون استفاده کنید.
https://www.npmjs.com/package/@qeydar/datepicker

@thealirexa 
@behnamhsn

**Comment by thealirexa** [comment]
@Abbasr7 
خیلی عالی بود عباس جان
به عنوان پیشنهاد اگه حالت انتخاب چند تایی تاریخ و همچنین امکان نمایش چند ماه کنار همدیگه رو هم داشته باشیم عالی میشه
